spring:
  application:
    name: client-service

server:
  port: 8082

spring.datasource:
  url: jdbc:mysql://localhost:3306/bd-client?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password:

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8090/realms/Gestion-Cafiteria-ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
